apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-go-app
  template:
    metadata:
      labels:
        app: sample-go-app
    spec:
      containers:
      - name: sample-go-app
        image: prashanna313/go_sample:latest
        ports:
        - containerPort: 8080